### ISSUE TITLE
User guide not imported

### ISSUE THREAD

**Issue by PaulHancock** [PaulHancock/Aegean#1]
The Aegean user guide has not been imported as it was not part of the SVN repository. The guid is out of date and needs to be remade. Github wiki is probably the best place to put the updated version of the user guide.

**Comment by taramurphy** [comment]
Is there a user guide yet?

**Comment by PaulHancock** [comment]
There is a user guide that was written for a very old version of Aegean. The guide is probably more wrong than it is right so I won't link to it here. Now that the development of the Aegean core features has slowed I will find some time to write a user guide. It will be based on the content of the wiki.
