### ISSUE TITLE
SR6 Default Compression

### ISSUE THREAD

**Issue by nhurleywalker** [PaulHancock/Aegean#106]
Hi,

Would it be possible for the default compression factor that SR6 applies be the same that BANE would apply in the same circumstance? At the moment, if you don't give a factor, SR6 fails with an error. I could go into the code for BANE and figure out what the compression factor I should be applying would be, but it would be neater to be in the code itself.

Thanks!
Natasha

**Comment by PaulHancock** [comment]
Bane will use 4x the beam size as it's default grid spacing, and the grid spacing is what is used as the compression factor. Therefore SR6 should use this same factor.
