### ISSUE TITLE
find_islands does not use region/mask from --region option

### ISSUE THREAD

**Issue by Sunmish** [PaulHancock/Aegean#114]
The new `find_islands` function does not use a region/mask as supplied by `--region`, and the region/mask is not being used anywhere else. Adding something like the following from `_gen_flood_wrap` seems to work as well as it did before:

```python
...
island.calc_bounding_box(np.array(np.nan_to_num(data_box), dtype=bool), offsets=[xmin, ymin])

if global_data.region is not None:
    y, x = np.where(snr[xmin:xmax, ymin:ymax] >= flood_clip)
    yx = list(zip(y + ymin, x + xmin))
    ra, dec = global_data.wcshelper.wcs.wcs_pix2world(yx, 1).transpose()
    mask = global_data.region.sky_within(ra, dec, degin=True)
    if not np.any(mask):
        continue
...
```
with `global_data` being supplied as an argument to `find_islands`, or just taking `global_data.region` and `global_data.wcshelper`. 

There seems to be implementation of this in `_gen_flood_wrap` used in `estimate_lmfit_parinfo`, but is at present hard-coded to not trigger and would not be used in all cases. In any case, the masking should occur prior to attempting to fit.

**Comment by PaulHancock** [comment]
fixed by #165
