### ISSUE TITLE
Regions outputted with --island are island bounding boxes, not contours

### ISSUE THREAD

**Issue by zhangxiang-planet** [PaulHancock/Aegean#117]
The issue was found with Aegean version 2.2.0/2.2.1.

Previously (not sure which Aegean version, though), when I do 
**aegean --autoload FITSFILE --island --table OUTPUT.reg**
I would get an isle.reg file for the island contours (the white polygon). 
![2114-4529 5500 previous](https://user-images.githubusercontent.com/22098261/82972836-8c2a8200-a008-11ea-913b-ec44e99ec179.png)

But currently, the file gives rectangles which might be island bounding boxes:
![2114-4529 5500 p2 current](https://user-images.githubusercontent.com/22098261/82972923-bda34d80-a008-11ea-8282-5482457b98fe.png)

**Comment by PaulHancock** [comment]
Thanks for your report. I've now fixed this bug as of Aegean 2.2.2 (4302ae9)
