### ISSUE TITLE
AeRes masking (--mask) adds components to the image as well as masking areas.

### ISSUE THREAD

**Issue by todoherty** [PaulHancock/Aegean#134]
When using the --mask option of AeRes to mask sources from the input catalogue the image is altered aside from the masking. In the attached image, which displays the model.fits file created by AeRes, multiple ellipses can be seen. These are the sources modeled by AeRes, and the pink region is the location of the nans (which are what is masked). However, we can see that around the nans is non-zero, and these non-zero components are added to the image. This can cause issues when source finding as it can boost the signal to noise around the masked areas above the detection threshold.
![aeres_error](https://user-images.githubusercontent.com/61398359/88909561-dd1b5880-d28d-11ea-8511-bb57291aa409.PNG)

**Comment by PaulHancock** [comment]
This is a good demonstration of the issue that I was trying to describe in #131. I have since fixed this bug!
