### ISSUE TITLE
Polarization cubes

### ISSUE THREAD

**Issue by as595** [PaulHancock/Aegean#138]
Hi Paul, is there a standard way to deal with polarisation cubes or should each stokes parameter be treated as a slice?

**Comment by PaulHancock** [comment]
Currently each slice of a cube is treated independently so the only option is to source find on each polarisation separately. Maybe you could use the stokes I catalogue to perform priorized fitting on the Q/U/V images to get a consistent position/shape across all polarizations.

**Comment by as595** [comment]
ah ok, that's what I've been doing already - just wanted to make sure I hadn't missed a trick somewhere. thanks!
