### ISSUE TITLE
Ubuntu 18.04 anaconda python 3.7.3 issues ?

### ISSUE THREAD

**Issue by stopsdj** [PaulHancock/Aegean#139]
I have created a virtual environment using anaconda python 3.7.3 on a system running Ubuntu 18.04.  I have installed
the stable aegeantools using "pip install AegeanTools" which seems to complete sucessfully. A colleague then attempts to use the
installation with MEERKAT-GPS data and encounters problems (below). It has been suggested that the problem lies with aegean version issues and that reverting to aegeantools 2.0.2 might work
 
2) For AEGEAN, the problem seems to be to do with the WCS - the program
starts but then quickly fails with a message:

"WCS does not have longitude type of 'RA', therefore (ra, dec) data can not
be returned"

Have you any thoughts on this ?

Thanks and Best Wishes

David

**Comment by PaulHancock** [comment]
Does MEERKAT-GPS refer to a galactic plane survey with Meerkat? It may be that the input data have coordinates that are lat/long instead of ra/dec, which is causing the error that you see.

Aegean shouldn't fall over when you use galactic coordinates, that's not the intended behavior.

**Comment by PaulHancock** [comment]
After some testing I can confirm that the issue above is due to the input file having coordinates in galactic coordinates instead of equatorial coordinates.
