### ISSUE TITLE
Suggestions for BANE noise characterization

### ISSUE THREAD

**Issue by PaulHancock** [PaulHancock/Aegean#159]
Suggestions:

1. BANE currently does up to 3 rounds of sigma clipping to determine the mean and std of the image pixels within a box. The scipy version of sigmaclip iterates until no additional pixels are clipped, however this function doesn't return the mean value, which would require BANE to do another calculation. **Suggest:** Copy the scipy code, alter it to return the (mean,std) and replace the existing BANE code.
2. bkg/noise could be computed by fitting the pixel histogram directly. The bkg/noise would be the mean/std of a Gaussian. The contribution of source pixels would need to be modelled as well. Currently not sure what the functional form would be.
3. BANE could be provided with multiple characterisation functions, and then the user can choose which is appropriate for the task. This would allow for new functions to be created that would characterise non-Gaussian distributions, such as the Ricean, or Poisson distributions that are seen in total linear polarisation or optical images.

**Comment by tjgalvin** [comment]
I have implemented option 1 in #160. My toy data suggests it works well, and has removed the pronounced bright boxes in our test data.

**Comment by PaulHancock** [comment]
#160 was merged so I can now close this issue.
