### ISSUE TITLE
Mask a fits file using another fits file as input

### ISSUE THREAD

**Issue by PaulHancock** [PaulHancock/Aegean#16]
Desired usage is:
- `mask.fits` contains image values that are either 1/0, where 1 means good data, and 0 means bad.
- `file.fits` contains actual image information, not all of which is useful.
- `masked.fits` is a file that is effectively the useful regions of file.fits

Suggested use case:
`MIMAS.py --fitsmask mask.fits file.fit masked.fits`
or
`aegean.py file.fits --mask mask.fits [other options]`

**Comment by pmanojlovic** [comment]
Hi Paul,

Something like mkmask (http://www.public.asu.edu/~rjansen/linux/mkmask_hlp.html) may be useful for creating fits masks using ds9 regions, and then applied using something like:
```python
test = np.empty(img.shape)
for i, m in np.ndenumerate(msk):
    if m > 0 and not np.isnan(img[i[0]][i[1]]):
        test[i[0]][i[1]] = float('nan')
    else:
        test[i[0]][i[1]] = img[i[0]][i[1]]

image[0].data[0][0] = test
image.writeto(prefix+'masked.fits', overwrite=True)

image.close()
mask.close()
```
where _img_ and _msk_ are the data array from their respective fits files.

![Screenshot](https://user-images.githubusercontent.com/10542066/42259811-5deb9d00-7fa5-11e8-962d-867e2e10ae80.png)

**Comment by pmanojlovic** [comment]
Sorry Paul, the screenshot was just to demonstrate the application of the mask but you've got the idea. Unfortunately I couldn't find any convenient method to create fits masks in python so I used mkmask (linked in the previous post) which can create fits masks out of arbitrary ds9 region files. It assigns 0=good and 1=bad by default but may be changed as desired.

Glad this was helpful!

**Comment by PaulHancock** [comment]
Even thought the requested functionality doesn't exist in MIMAS, I believe that it can be achieved in a two step process as follows:

Convert the first image into a mask:
`MIMAS --mask2mim mask.fits region.mim`
Use that mask to mask the second image:
`MIMAS --maskimage region.mim file.fits masked.fits`

This is not a pixel-to-pixel perfect masking process since there will be some edge effects due to the healpix pixelization, but it is a general solution that can be used even when images don't have a one to one mapping of pixels.
