### ISSUE TITLE
remove support for calculating and reporting of "condon" errors

### ISSUE THREAD

**Issue by PaulHancock** [PaulHancock/Aegean#174]
"Condon errors" were initially included as a way to report errors when I was unable to convert the fitting covariance matrix into parameter errors.
Now that parameter errors can be directly and accurately computed from the fitting process there is no need for the "condon" errors.
Additionally the "condon" errors were at best an approximation based on a single instrument and fitting routine, and do not apply in all (most?) cases.

**Comment by tjgalvin** [comment]
While this is fresh, would there be any way to save the covariance matrices themselves? It would be useful in some cases where nearby components are increasinly blended together. As I understand aegean at the moment the off-diagonal errors are not preserved in the output.
