### ISSUE TITLE
How to evaluate the noise of fits image?

### ISSUE THREAD

**Issue by LKHZ** [PaulHancock/Aegean#192]
Hello, I'm going to evaluate some of my fit images. I read your BANE documents, but I still don't know how to use them. Can you give me some suggestions? Thank you.

**Comment by PaulHancock** [comment]
Hi,

Once you install AegeanTools you should have a new command line tools available called `BANE`. You can run it like this:
```
BANE my_image.fits
```
and it will create files `my_image_bkg.fits` and `my_image_rms.fits` which are the background and noise maps.

See https://github.com/PaulHancock/Aegean/wiki/BANE for more detailed description on how BANE works and how to use it.

Paul.

**Comment by LKHZ** [comment]
Thank you very much for your reply. In the way you said, I successfully ran the program and generated the background image.
