### ISSUE TITLE
aegean unable to read in bkg and rms from BANE in v2.3.0

### ISSUE THREAD

**Issue by astrokatross** [PaulHancock/Aegean#193]
Seems to be an issue with indexing for newer version where it cannot read in the bkg or rms from BANE. 

Final error: 
`IndexError: Illegal index None`

Full log:
[aegean_log.txt](https://github.com/PaulHancock/Aegean/files/10088449/aegean_log.txt)

**Comment by PaulHancock** [comment]
The indexing is part of the issue, but can be solved by setting `--slice=0` (which I'll now set as the default).

A larger issue is that sending Aegean a compressed version of the background and noise images, no longer un-compresses them automatically.
For example:
```
$ aegean --slice 0 --autoload ~/Downloads/1286818576_deep-0000-image-pb_warp.fits
aegean:INFO This is Aegean 2.3.0-(2022-08-17)
aegean:INFO Found 8 cores
aegean:INFO Using 8 cores
aegean:INFO Found background ~/Downloads/1286818576_deep-0000-image-pb_warp_bkg.fits
aegean:INFO Found noise ~/Downloads/1286818576_deep-0000-image-pb_warp_rms.fits
aegean:INFO Finding sources.
source_finder:INFO Loading background data from file ~/Downloads/1286818576_deep-0000-image-pb_warp_bkg.fits
source_finder:ERROR file ~/Downloads/1286818576_deep-0000-image-pb_warp_bkg.fits is not the same size as the image map
source_finder:ERROR ~/Downloads/1286818576_deep-0000-image-pb_warp_bkg.fits= (382, 382), image = (8000, 8000)
```

**Comment by PaulHancock** [comment]
If you install v2.3.0 from github (date 2022-11-29 or later) this issue will be fixed.
