### ISSUE TITLE
Aegean sometimes takes a very long time to fit an island

### ISSUE THREAD

**Issue by PaulHancock** [PaulHancock/Aegean#20]
Problem: 
Occasionally Aegean will seem to freeze for a very long time. After a few hours Aegean will finally produce output. The output suggests that a very large island is being fit.

Cause:
It seems that the primary cause of this problem is large islands. Islands that have ~30 or more pixels will take a long time to fit regardless of the number of components being fit. This is due to the use of the covariance matrix which scales as the square of the number of pixels in the island.

**Comment by PaulHancock** [comment]
I have added a new test image to the repository that will replicate this problem with minimal effort.
To see this problem in action:
`aegean.py --autoload Test/Images/1904-66_SIN.fits` (should take a few seconds to complete)
versus
`aegean.py --autoload Test/Imags/Bright.fits` (takes a lot longer to complete, never been bothered to wait for it but it's at least a few minutes).

The cause of the problem is the covariance matrix. Setting the covariance matrix to the ID matrix makes no difference, so it is due to the matrix multiplications involved. Setting the the parameters B,C to be None in aegean.fit_island() will cause the fitting to not use any covariance matrix and make the above two test cases run in a few seconds each.

**Comment by torrance** [comment]
Hi Paul,

I am testing AEGEAN against a number of other source finding algorithms on large and diffuse (synthetic) gaussian sources. I am finding runtimes on moderate size images (~8000px x 8000px) with sources up to 250px in 1-sigma width takes days to run, and vast amounts of memory. On 10,000 x 10,000px images (still with maximum source size of 250px width) all 96Gb of system memory is eventually exhausted and the program quits.

Is this tractable or simply beyond the limits of what AEGEAN is capable of doing? The primary characteristic I care about is simply location (or more precisely, the bounding ellipse incorporating a 'sufficiently' large enough area of the source); the peak and integrated flux are the secondary characteristics but happy to forgo these if I can get location data running in a reasonable timeframe.

**Comment by torrance** [comment]
As you suggested, setting B, C to None in https://github.com/PaulHancock/Aegean/blob/master/AegeanTools/source_finder.py#L1235 dramatically speeds things up.

So what have we lost here? We still have figures for errors on all the characterisation values — but are these figures less accurate?

**Comment by PaulHancock** [comment]
Torrance,

Using B=C=None will mean that the fitting process is not taking the correlated nature of the data into account. It will thus result in a fit that is more biased, and uncertainties that are underestimated.

The reason that the fit takes so long on the islands that you mention is because they have such a large number of pixels in them. The B and C matrices are NxN in size, where N is the total number of pixels in the island. The extra time in the fitting when B,C are not None, is just the time that it takes to multiply this NxN matrix by your data/model.

I am thinking about ways that will allow a user to set a maximum size for the C/B matrices so that you can put a cap on how long it takes to fit an individual island. 

Paul.
