### ISSUE TITLE
Filename is given incorrectly in BANE's logging message

### ISSUE THREAD

**Issue by nhurleywalker** [PaulHancock/Aegean#22]
Typical output looks like:

7025:INFO This is BANE v1.2-(2015-06-24)
7025:INFO using grid_size (17, 17), box_size (102, 102)
7025:INFO on data shape (10801, 15748)
7025:INFO using 8 cores
7025:INFO done
7025:INFO Wrote <open file '<fdopen>', mode 'w+b' at 0x191eae0>

output is produced as expected, i.e. a file like _bkg.fits.

**Comment by PaulHancock** [comment]
The strange filename is a temporary file that is written before BANE starts a second pass of the data.

If this is the only output that is given then it would appear that BANE was halted before it completed.

Was a _bkg.fits file actually produced and is there any further output that was given?

**Comment by PaulHancock** [comment]
This issue was later found to be due to BANE being terminated by the host environment before it was complete.
