### ISSUE TITLE
Stop to process when aegean can not found BEAM info when handle VLA data

### ISSUE THREAD

**Issue by shaoguangleo** [PaulHancock/Aegean#28]
Hi Paul,
We encounter a issue when we processing VLA data using aegean, which do not have BEAM informations.
Such as `BMAJ`,`BMIN` and `BPA` key.

So the simplest way is to dig out these key from `HISTORY` section and then write them to the FITS   header @ly201601.

Then it works good.

So it maybe useful if you can add this script before processing FITS data.

Test scripts can refer #27.

**Comment by PaulHancock** [comment]
Shao,

When you say "VLA data" do you actually mean "data processed with AIPS/CASA"?

The BMIN/BMAJ/BPA keywords are not part of the fits standard so different software have done different things to encode this information. Unfortunately some chose to put the information in the history cards, which is a pain.

There are two approaches that we could take: 
1. When BMAJ/BMIN/BPA are not found as keywords, look through the history cards for the corresponding information. This could be done transparently.
2. Have a script that simply pulls the information from the history and puts it into the corresponding keywords.

You are suggesting a script that will do option 2. Both of these would work for Aegean however I think that option 2 would be a more general use tool that would be of use to other programs also.

I have looked at your pull request and see that you have the functionality there. I'll include this code, however I'll add the functionality in a slightly different way: the header updating will go into the fits_image module, and i'll write a command line wrapper to go into the scripts directory.

Paul.

**Comment by PaulHancock** [comment]
As of 8bdbdc9 I have made the following changes wich I think address this ticket:
- I have accepted the pull request, and integrated your solution into AegeanTools 
  - The fixing of the fits header is done by AegeanTools.fits_image.fix_aips_header
- I have refactored the fix_beam.py code and moved it into the scripts directory.

You can now find fix_beam.py in the master branch of this repository.

Thanks for your input @shaoguangleo !
