### ISSUE TITLE
Units of a,b,psf_a,psf_b not matching documentation

### ISSUE THREAD

**Issue by Cameron-Van-Eck** [PaulHancock/Aegean#45]
So I'm getting a very unexpected result: I'm running Aegean on some simulated data, and looking at the output catalog, and the values for a, b, psf_a, and psf_b are all very unexpected. In the documentation (https://github.com/PaulHancock/Aegean/wiki/Output-Formats) it says all these quantities are in degrees, but if I compare the output values (particularly for the psf) to the input FITS header (again, particularly the beam keywords), the numbers are completely different.
To be specific, here's my FITS header:
BMAJ    =           0.00406575                                                  
BMIN    =    0.003565888888889                                                  
BPA     =              88.6496   
                                               
And here's my table output (via my ipython-based exploration of the data):
In [37]: meanQ_cat['psf_a'][0]
Out[37]: 14.636699999999999
In [38]: meanQ_cat['psf_b'][0]
Out[38]: 12.837200000000399
In [39]: meanQ_cat['psf_pa'][0]
Out[39]: 88.649600000000007

Values of a,b, and pa are all consistent with the PSF values for most fitted sources.
The PA is fine, but in the major/minor axes there's a factor of 3600 difference, which I think suggests the cause: a missing conversion from arcseconds to degrees? (Or, alternatively, one could simply change the documentation of the outputs...)

Aside from this, everything seems to work great so far, so thank you for your hard working developing this.

**Comment by PaulHancock** [comment]
Hi Cameron,

Thanks for your attention to detail. I have changed the documentation to reflect what the code is doing so that the two are now consistent.

Paul.
