### ISSUE TITLE
Documentation for Priorized Fitting

### ISSUE THREAD

**Issue by nhurleywalker** [PaulHancock/Aegean#55]
The wiki needs to be clearer about how you can input a catalogue which has psf_ columns instead of specifying --ratio or --catpsf when performing priorized fitting:

https://github.com/PaulHancock/Aegean/wiki/Priorized-Fitting

Better --help text also appreciated, or a link to the wiki.

**Comment by PaulHancock** [comment]
The wiki has been updated to describe which catalogue columns are required/used.

The --help text has been updated to be more helpful.

Please re-open this ticket if there are further improvements to be made.
