### ISSUE TITLE
document input region format

### ISSUE THREAD

**Issue by caseyjlaw** [PaulHancock/Aegean#74]
I am interested in using aegean to model a single source on a FITS image. I use saods9 for viewing and I saw that aegean writes ds9 region files. I thought that it would parse them also.
However, in both python 2 or 3, I get this error when trying to read a file:

```
Traceback (most recent call last):
  File "/Users/caseyjlaw/anaconda/bin/aegean", line 372, in <module>
    docov=options.docov, cube_index=options.slice)
  File "/Users/caseyjlaw/anaconda/lib/python2.7/site-packages/AegeanTools/source_finder.py", line 1479, in find_sources_in_image
    verb=True, mask=mask, lat=lat, psf=imgpsf, blank=blank, docov=docov, cube_index=cube_index)
  File "/Users/caseyjlaw/anaconda/lib/python2.7/site-packages/AegeanTools/source_finder.py", line 683, in load_globals
    self.global_data.region = cPickle.load(open(mask, 'rb'))
cPickle.UnpicklingError: invalid load key, '#'.
```

What format is expected?

**Comment by caseyjlaw** [comment]
And just to be clear, aegean is basically working for me out of the box. Very nice work!

**Comment by PaulHancock** [comment]
The format that is expected is a file created by `MIMAS`. 
I'm working on allowing `MIMAS` to convert (some) ds9 region files into the required format.

**Comment by PaulHancock** [comment]
I have also updated the [wiki ](/PaulHancock/Aegean/wiki/Simple-usage) with this info.
