### ISSUE TITLE
Using BANE on image cube

### ISSUE THREAD

**Issue by jrcallingham** [PaulHancock/Aegean#86]
Hi Paul,

I am playing around with image cubes, and while Aegean has an option to source find on a particular slice of the cube, I can not find a similar functionality with BANE (ie make background/rms images for a particular slice, not just the first one). Am I missing it or can I make this a feature request for BANE?

Joe

**Comment by PaulHancock** [comment]
You are not missing anything. BANE doesn't (yet) have this same feature. I'll mark it as a feature request :smile:

**Comment by PaulHancock** [comment]
This is now a thing!

**Comment by jrcallingham** [comment]
Awesome. Thanks Paul!
