### ISSUE TITLE
Different input formats for fixed-position source-characterisation mode

### ISSUE THREAD

**Issue by nhurleywalker** [PaulHancock/Aegean#9]
Sometimes I source-find on a master image to get a bunch of sources. I then play around with these in e.g. TopCat and make some sub-selections based on various criteria. When I write out from standard software like TopCat, I can only use standard output formats like vot and fits. However, if I then want to use that catalogue as an input to futher source-finding/fitting with Aegean, I need to use Aegean's native ".cat" format, which is not easy to create. Would it be possible to use other format tables as an input to Aegean's fixed-position source-characterisation mode?

**Comment by PaulHancock** [comment]
The dev branch of Aegean will now allow you to read the following formats that were written by Aegean (or at least have ra/dec column headers):
csv, tab, tex, vo, vot, xml, cat.

.html is not supported and you should feel bad for trying to use html as a data format
