### ISSUE TITLE
Ground truth cross-matching

### ISSUE THREAD

**Issue by andreasalamanos** [PaulHancock/Aegean#90]
Not the right place to ask, 

But what is there somewhere the routine to cross match the results of Aegean with the ground truth? 

The function is already mentioned on the paper

**Comment by PaulHancock** [comment]
In the paper I simulated a catalogue of sources, then made images from these catalogues using AeRes, before finally running Aegean to create a 'recovered' catalogue. Comparing the ground truth catalogue to the recovered catalogues was done using the [stilts](http://www.star.bris.ac.uk/~mbt/stilts/) command line tool.

**Comment by rasputin1917** [comment]
Very helpful, Thanks!!
