### ISSUE TITLE
Problems with Aegean install

### ISSUE THREAD

**Issue by jrcallingham** [PaulHancock/Aegean#94]
Hey Paul,

I have a summer student that I have got to install Aegean to do some source characterisation. The install goes fine (with both git cloning and pip install). BANE also works fine. However, when we attempt to run Aegean, we get the following error (basic command we issued below too):

aegean --table LP212-62_P156+42_nchan20-0000-I-image11.fits LP212-62_P156+42_nchan20-0000-I-image.fits

aegean:INFO This is Aegean 2.0.2-(2018-07-04)
aegean:INFO Found 4 cores
aegean:INFO Using 4 cores
aegean:INFO Finding sources.
source_finder:INFO Calculating curvature
source_finder:INFO Calculating background and rms data                                                           Traceback (most recent call last):
File "/usr/local/bin/aegean", line 372, in <module> docov=options.docov, cube_index=options.slice)
File "/usr/local/lib/python2.7/dist-packages/AegeanTools/source_finder.py", line 1479, in find_sources_in_image verb=True, mask=mask, lat=lat, psf=imgpsf, blank=blank, docov=docov, cube_index=cube_index)
File "/usr/local/lib/python2.7/dist-packages/AegeanTools/source_finder.py", line 716, in load_globals self._make_bkg_rms(mesh_size=20, forced_rms=rms, forced_bkg=bkg, cores=cores)
File "/usr/local/lib/python2.7/dist-packages/AegeanTools/source_finder.py", line 955, in _make_bkg_rms for ymin, ymax, xmin, xmax, bkg, rms in queue:
TypeError: instance has no next() method 

She is running it on Ubuntu 18.04 and using python 2.7. Sorry if this is straight forward problem, but I can not seem to find where the issue is occuring. Is this a silly question?

Joe

**Comment by PaulHancock** [comment]
Joe, I recall seeing something like this before but right now can't remember exactly how I ran into this error.

The traceback indicates that Aegean is trying to compute the bkg/rms internally which I don't recommend, use BANE to do this as it's more accurate and reliable, and then feed the outputs into Aegean with the `--background` and  `--noise` options. This should get around your problem in the short term by just avoiding the code that is causing the issue. 

I'll have to dig into this code a bit more to figure out what the error might be. If you could send a minimum working example that demonstrates this issue (via email, not here) that would be great. Include the output of `pip freeze` so I can see what versions of various things you are running, as well as a subset of the image which causes the error.

**Comment by jrcallingham** [comment]
Will do. We have already run BANE (BANE works fine) and tried running aegean with --autoload but get a similar error. I was just trying to give you a minimum working example. I will email you the error with --noise and --background specified specifically (obviously the same error with --autoload).
