### ISSUE TITLE
Output island masks and bounding boxes

### ISSUE THREAD

**Issue by MatthewJA** [PaulHancock/Aegean#95]
In using PyBDSF, I've been enjoying that for each island it creates a bounding box and a mask for which pixels are in the island in that box. I think Aegean encounters everything one would need to assemble this info while source-finding, so it'd be great if it output the bounding boxes and masks.

(A simple useful output would be the (x, y) coordinate of the corner of the bounding box in pixels — Aegean already outputs the width and height in pixels.)

**Comment by Jordatious** [comment]
@MatthewJA, option `--island` should cover this. You can write a ds9 region file with the island boundaries, for instance.

**Comment by MatthewJA** [comment]
The `--island` option outputs an island catalogue, yes, but I can't seem to find a way to write a region file (per island). I found that `AeRes` can output a mask, but it's not the same thing.

**Comment by Jordatious** [comment]
This should do it:

`aegean --island --table=table.fits,table.reg image.fits`

This will give you a file called `table_isle.reg`, which has the island boundaries, in addition to one with the fitted components (and also fits catalogues of the two). I just ran that using Aegean 2.0.2-(2018-07-19), and am able to overlay the ds9 region file for the islands.

Or are you after something else?

**Comment by PaulHancock** [comment]
Thanks @caseyjlaw this is a good point!

I have updated the [wiki](https://github.com/PaulHancock/Aegean/wiki/Output-Formats) to indicate that `.reg` files are a valid output format, and to describe what the overlays will look like.
